# For real pirates out there
[[keybind]]
sound = "sounds/lockin.wav"
keys = ["KEYS_LETTERS", "KEYS_DIGITS", "KEYS_SPECIAL"]

[[keybind]]
sound = "sounds/load.wav"
keys = [ "KEYS_CONTROL" ]

[[keybind]]
sound = "sounds/fire.wav"
keys = ["KEY_ENTER"]

[[keybind]]
sound = "sounds/reload.wav"
keys = ["KEY_SPACE"]

[[keybind]]
sound = "sounds/spit.wav"
keys = ["KEY_BACKSPACE", "KEY_DELETE"]